#nome da aplicação
spring.application.name=usuario
#url do banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/db_usuario
#nome do usuario
spring.datasource.username=postgres
#senha do banco
spring.datasource.password=1234
# se não tiver a tabela ele cria , se tem ela apenas atualza
spring.jpa.hibernate.ddl-auto=update
# print da informação do que acontece no bancp
spring.jpa.show-sql=true
# configuração de dialeto dop hibernate do banco de dados postgree
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

